In [2]:
import numpy as np
age=np.array([24,28,32,34,36])
age

array([24, 28, 32, 34, 36])

In [3]:
age=np.array([[24], [28], [32], [34], [36]])
age

array([[24],
       [28],
       [32],
       [34],
       [36]])

In [9]:
data=np.array([[24,170,84,100],[28,168,80,120],[32,171,75,105],[34,170,78,108],
               [36,164,80,100]])
data

array([[ 24, 170,  84, 100],
       [ 28, 168,  80, 120],
       [ 32, 171,  75, 105],
       [ 34, 170,  78, 108],
       [ 36, 164,  80, 100]])

In [28]:
data[:,0:4]

array([[ 24, 170,  84, 100],
       [ 28, 168,  80, 120],
       [ 32, 171,  75, 105],
       [ 34, 170,  78, 108],
       [ 36, 164,  80, 100]])

In [7]:
np.mean(data[ : ,0:1])
print("mean: ",np.mean(data[ : ,0:1]))
print("median: ",np.median(data[ : ,0:1]))
print("standard deviation: ",np.std(data[ : ,0:1]))
print("variance: ",np.var(data[ : ,0:1]))

mean:  30.8
median:  32.0
standard deviation:  4.308131845707603
variance:  18.56


In [8]:
data[ : ,0:2]

array([[ 24, 170],
       [ 28, 168],
       [ 32, 171],
       [ 34, 170],
       [ 36, 164]])

In [9]:
data[ : ,0:3]

array([[ 24, 170,  84],
       [ 28, 168,  80],
       [ 32, 171,  75],
       [ 34, 170,  78],
       [ 36, 164,  80]])

In [10]:
data[ : ,0:4]

array([[ 24, 170,  84, 100],
       [ 28, 168,  80, 120],
       [ 32, 171,  75, 105],
       [ 34, 170,  78, 108],
       [ 36, 164,  80, 100]])

In [11]:
data[ : ,0:3:2] #to skip the second column

array([[24, 84],
       [28, 80],
       [32, 75],
       [34, 78],
       [36, 80]])

In [12]:
#creating random numbers
x1=np.random.randint(10,20, size=6)
x1

array([11, 15, 15, 18, 12, 19], dtype=int32)

In [13]:
x1.ndim

1

In [17]:
x2=np.random.randint(10,20,size=(3,4))
x2

array([[15, 16, 14, 17],
       [11, 16, 11, 13],
       [14, 17, 15, 19]], dtype=int32)

In [19]:
x3=np.random.randint(10,20,size=(2,3,4))
x3

array([[[12, 15, 19, 18],
        [10, 15, 15, 10],
        [19, 14, 10, 16]],

       [[13, 15, 15, 19],
        [14, 16, 12, 12],
        [19, 15, 19, 16]]], dtype=int32)

In [20]:
x3.ndim

3